server:
  port: 8010

# spring.application.name: 当前服务提供者在Eureka Server 上的名称
spring:
  application:
    name: producer

# eureka.client.service-url.defaultZone: 注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
# eureka.instance.prefer-ip-address: 是否将当前服务的ip注册到Eureka Server上。
  instance:
    prefer-ip-address: true
